apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  containers:
  - image: localhost:5000/nginx:1.21.0
    imagePullPolicy: IfNotPresent
    name: nginx
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-sbomscanner-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
